import { formatMoney, formatPercent } from './money'
import type { FinancialSummary } from './financials'
import type { RevenueSummary } from './revenue'
import type { ValidationIssue } from './validation'

export type AlertLevel = 'critical' | 'warning' | 'good'

export interface Alert {
  level: AlertLevel
  message: string
}

/**
 * Deterministic alert engine (spec §41): numbers are interpreted with fixed
 * rules, not generated by a model. Thresholds here are Phase 1 defaults and
 * intentionally simple; Phase 2+ adds break-even/staffing-cliff/DSCR alerts.
 */
export const computeAlerts = (
  revenue: RevenueSummary,
  financials: FinancialSummary,
  validationIssues: ValidationIssue[],
): Alert[] => {
  const alerts: Alert[] = []

  for (const issue of validationIssues) {
    if (issue.severity === 'CRITICAL') alerts.push({ level: 'critical', message: issue.message })
    else if (issue.severity === 'ERROR') alerts.push({ level: 'critical', message: issue.message })
    else alerts.push({ level: 'warning', message: issue.message })
  }

  if (financials.ebitdaMonthly < 0) {
    alerts.push({
      level: 'critical',
      message: `Operating at a loss: EBITDA is ${formatMoney(financials.ebitdaMonthly)}/month.`,
    })
  } else {
    alerts.push({
      level: 'good',
      message: `Operating at a profit: EBITDA is ${formatMoney(financials.ebitdaMonthly)}/month.`,
    })
  }

  if (financials.payrollPctOfRevenue > 0.6 && revenue.totalMonthlyRevenue > 0) {
    alerts.push({
      level: 'warning',
      message: `Payroll represents ${formatPercent(financials.payrollPctOfRevenue)} of revenue.`,
    })
  }

  if (revenue.occupancy < 0.7 && revenue.totalCapacity > 0) {
    alerts.push({
      level: 'warning',
      message: `Occupancy is ${formatPercent(revenue.occupancy)} — ${revenue.availableSpaces} spaces are empty (${formatMoney(revenue.lostMonthlyRevenue)}/month in unrealized revenue).`,
    })
  }

  return alerts
}
