import type { BreakEvenResult } from './breakEven'
import type { FinancialSummary } from './financials'
import { formatMoney, formatPercent } from './money'
import type { RevenueSummary } from './revenue'
import type { StaffingSummary } from './staffing'
import type { StaffingCliff } from './staffingCliffs'
import type { AgeGroup } from './types'
import type { ValidationIssue } from './validation'

export type AlertLevel = 'critical' | 'warning' | 'good'

export interface Alert {
  level: AlertLevel
  message: string
}

/**
 * Deterministic alert engine (spec §41): numbers are interpreted with fixed
 * rules, not generated by a model.
 */
export const computeAlerts = (
  revenue: RevenueSummary,
  financials: FinancialSummary,
  validationIssues: ValidationIssue[],
  staffing: StaffingSummary,
  nextCliffs: StaffingCliff[],
  breakEven: BreakEvenResult,
  ageGroups: AgeGroup[],
): Alert[] => {
  const alerts: Alert[] = []

  for (const issue of validationIssues) {
    if (issue.severity === 'CRITICAL' || issue.severity === 'ERROR') alerts.push({ level: 'critical', message: issue.message })
    else alerts.push({ level: 'warning', message: issue.message })
  }

  if (financials.ebitdaMonthly < 0) {
    alerts.push({ level: 'critical', message: `Operating at a loss: EBITDA is ${formatMoney(financials.ebitdaMonthly)}/month.` })
  } else {
    alerts.push({ level: 'good', message: `Operating at a profit: EBITDA is ${formatMoney(financials.ebitdaMonthly)}/month.` })
  }

  if (financials.payrollPctOfRevenue > 0.6 && revenue.totalMonthlyRevenue > 0) {
    alerts.push({ level: 'warning', message: `Payroll represents ${formatPercent(financials.payrollPctOfRevenue)} of revenue.` })
  }

  if (revenue.occupancy < 0.7 && revenue.totalCapacity > 0) {
    alerts.push({
      level: 'warning',
      message: `Occupancy is ${formatPercent(revenue.occupancy)} — ${revenue.availableSpaces} spaces are empty (${formatMoney(revenue.lostMonthlyRevenue)}/month in unrealized revenue).`,
    })
  }

  if (staffing.groupsWithUnknownRatio.length > 0) {
    const names = staffing.groupsWithUnknownRatio
      .map((id) => ageGroups.find((g) => g.id === id)?.name)
      .filter(Boolean)
      .join(', ')
    alerts.push({
      level: 'warning',
      message: `Child:staff ratio is UNKNOWN / NEEDS VERIFICATION for: ${names}. Staffing requirements and Break-Even for these groups are not yet verified.`,
    })
  }

  for (const cliff of nextCliffs) {
    alerts.push({
      level: 'warning',
      message: `Enrolling one more child in ${cliff.ageGroupName} triggers another required staff position (net impact: ${formatMoney(cliff.netMonthlyImpact)}/month).`,
    })
  }

  if (breakEven.hasCapacity) {
    if (breakEven.breakEvenExceedsCapacity) {
      alerts.push({
        level: 'critical',
        message: `Break-even enrollment exceeds licensed capacity at the current cost structure — this center cannot break even as configured.`,
      })
    } else if (breakEven.breakEvenOccupancy !== null && breakEven.breakEvenOccupancy >= 0.85) {
      alerts.push({
        level: 'warning',
        message: `Break-even requires ${formatPercent(breakEven.breakEvenOccupancy)} occupancy.`,
      })
    }
    if (breakEven.hasUnknownRatios) {
      alerts.push({
        level: 'warning',
        message: `Break-Even is a PRELIMINARY estimate — one or more group ratios are unverified, so staffing cost is extrapolated from planned staffing rather than a verified ratio.`,
      })
    }
  }

  return alerts
}
