/** Only `multiple_choice` is generated by Fase 7 — DATA_MODEL.md's `type` column allows more later. */
export type QuestionType = 'multiple_choice'
export type QuestionDifficulty = 'easy' | 'medium' | 'hard'

export interface QuestionSourceRef {
  documentId: string
  documentTitle: string
  pageStart: number
  pageEnd: number
}

/** Sent to the player while an attempt is in progress — never includes the answer. */
export interface AttemptQuestion {
  id: string
  type: QuestionType
  prompt: string
  choices: string[]
  selectedIndex: number | null
}

export interface AttemptDetail {
  id: string
  courseId: string
  courseTitle: string
  completedAt: string | null
  totalQuestions: number
  questions: AttemptQuestion[]
}

/** Sent once an attempt is finished — includes everything needed to review it. */
export interface ResultQuestion extends AttemptQuestion {
  correctIndex: number
  explanation: string
  sourceRefs: QuestionSourceRef[]
  isCorrect: boolean
}

export interface AssessmentResult {
  id: string
  courseId: string
  courseTitle: string
  score: number
  correctCount: number
  totalQuestions: number
  durationSeconds: number | null
  previousAverageScore: number | null
  questions: ResultQuestion[]
}

export interface AssessmentHistoryEntry {
  id: string
  courseId: string
  courseTitle: string
  score: number
  totalQuestions: number
  completedAt: string
}
